Repository feast-dev/feast-spark, pull requests merged in 2021-04, with the labels that each got.

#52 Fix avro serialization: reuse generated schema in advance
  spark/ingestion/src/main/scala/feast/ingestion/stores/bigtable/BigTableSinkRelation.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/bigtable/serialization/AvroSerializer.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/bigtable/serialization/Serializer.scala
  spark/ingestion/src/main/scala/feast/ingestion/validation/RowValidator.scala
Labels: approved, kind/bug, needs-kind, release-note-none, size/M

#53 Bump feast version to 0.9.5
  python/requirements-ci.txt
  python/setup.py
Labels: kind/housekeeping, ok-to-test, release-note-none, size/XS

#54 Better handling for invalid proto messages
  spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/utils/ProtoReflection.scala
  spark/ingestion/src/test/scala/feast/ingestion/StreamingPipelineIT.scala
Labels: approved, kind/housekeeping, release-note-none, size/M

#56 Fix dependencies for aws e2e
  infra/scripts/test-end-to-end-aws.sh
  infra/scripts/test-end-to-end-sparkop.sh
Labels: approved, do-not-merge/release-note-label-needed, needs-kind, size/XS

#55 Cassandra schema update should not fail when column exist
  spark/ingestion/src/main/scala/feast/ingestion/stores/cassandra/CassandraSinkRelation.scala
  spark/ingestion/src/test/scala/feast/ingestion/CassandraIngestionSpec.scala
Labels: approved, kind/bug, release-note-none, size/M

#58 Reuse stencil client between Spark Tasks
  spark/ingestion/src/main/scala/feast/ingestion/registry/proto/StencilProtoRegistry.scala
  spark/ingestion/src/main/scala/feast/ingestion/utils/ProtoReflection.scala
Labels: approved, kind/housekeeping, release-note-none, size/M

#57 Add project whitelist
  python/feast_spark/constants.py
  python/feast_spark/job_service.py
  python/tests/test_streaming_job_scheduling.py
  spark/ingestion/src/test/scala/feast/ingestion/SparkSpec.scala
Labels: approved, enhancement, kind/feature, lgtm, ok-to-test, release-note, size/L

#60 Bump spark version to 3.0.2
  infra/docker/spark/Dockerfile
  pom.xml
Labels: approved, kind/housekeeping, release-note-none, size/XS

#63 Configurable triggering interval from streaming ingestion
  python/feast_spark/constants.py
  python/feast_spark/pyspark/abc.py
  python/feast_spark/pyspark/launcher.py
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/bigtable/BigTableSinkRelation.scala
Labels: approved, kind/feature, release-note, size/S

#62 Migrate sparkop e2e tests to kf-feast cluster
  .prow.yaml
  infra/scripts/helm/k8s-jobservice.tpl.yaml
  infra/scripts/k8s-common-functions.sh
  infra/scripts/test-end-to-end-sparkop.sh
  tests/e2e/fixtures/client.py
Labels: approved, needs-kind, release-note-none, size/L

#65 Explicitly stop sparkSession on exception to prevent it stucking
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
Labels: approved, kind/housekeeping, release-note-none, size/XS

#66 Call admin.modifyTable only if table spec changes: preventing quota to be exceeded
  spark/ingestion/src/main/scala/feast/ingestion/stores/bigtable/BigTableSinkRelation.scala
  spark/ingestion/src/test/scala/feast/ingestion/BigTableIngestionSpec.scala
Labels: approved, kind/bug, lgtm, release-note-none, size/M

#59 Support for Schedule Spark Application
  infra/scripts/helm/k8s-jobservice.tpl.yaml
  infra/scripts/test-end-to-end-aws.sh
  infra/scripts/test-end-to-end-gcp.sh
  infra/scripts/test-end-to-end-local.sh
  infra/scripts/test-end-to-end-sparkop.sh
  protos/feast_spark/api/JobService.proto
  python/feast_spark/client.py
  python/feast_spark/job_service.py
  python/feast_spark/pyspark/abc.py
  python/feast_spark/pyspark/launcher.py
  python/feast_spark/pyspark/launchers/aws/emr.py
  python/feast_spark/pyspark/launchers/gcloud/dataproc.py
  python/feast_spark/pyspark/launchers/k8s/k8s.py
  python/feast_spark/pyspark/launchers/k8s/k8s_utils.py
  python/feast_spark/pyspark/launchers/standalone/local.py
  python/setup.py
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
  tests/e2e/conftest.py
  tests/e2e/test_job_scheduling.py
Labels: approved, kind/feature, lgtm, release-note, size/XL

#67 Bigtable sink (row level) metrics
  spark/ingestion/src/main/scala/feast/ingestion/stores/bigtable/BigTableSinkRelation.scala
  spark/ingestion/src/main/scala/org/apache/spark/metrics/source/BigTableSinkMetricSource.scala
Labels: approved, kind/housekeeping, release-note-none, size/M
