Repository feast-dev/feast-spark, pull requests merged in 2021-02, with the labels that each got.

#13 Build & push docker workflow for spark ingestion job
  .github/workflows/release.yml
  Makefile
  infra/docker/spark/Dockerfile
  pom.xml
Labels: do-not-merge/release-note-label-needed, needs-kind, size/L

#11 Fix Azure e2e tests
  .github/workflows/complete.yml
  README.md
  infra/scripts/azure-runner.sh
  infra/scripts/k8s-common-functions.sh
Labels: kind/housekeeping, release-note-none, size/M

#19 Update CI workflow
  Makefile
  python/requirements-ci.txt
Labels: kind/housekeeping, lgtm, release-note-none, size/S

#22 Add SparkClient as separate pytest fixture
  Makefile
  infra/scripts/aws-runner.sh
  tests/e2e/conftest.py
  tests/e2e/fixtures/client.py
  tests/e2e/test_historical_features.py
  tests/e2e/test_online_features.py
  tests/e2e/test_validation.py
  tests/e2e/utils/common.py
  tests/setup.cfg
Labels: kind/housekeeping, release-note-none, size/L

#23 Add protos and update CI
  Makefile
  infra/docker/jobservice/Dockerfile
  infra/scripts/test-end-to-end-gcp.sh
  pom.xml
  protos/feast_spark/api/JobService.proto
  protos/feast_spark/third_party/grpc/health/v1/HealthService.proto
  python/feast_spark/api/__init__.py
  python/feast_spark/client.py
  python/feast_spark/job_service.py
  python/feast_spark/third_party/__init__.py
  python/feast_spark/third_party/grpc/__init__.py
  python/feast_spark/third_party/grpc/health/__init__.py
  python/feast_spark/third_party/grpc/health/v1/__init__.py
  python/pyproject.toml
  python/requirements-ci.txt
  python/setup.cfg
  python/setup.py
  tests/e2e/conftest.py
  tests/e2e/fixtures/base.py
Labels: do-not-merge/release-note-label-needed, needs-kind, size/L

#16 Add project filter to list jobs
  python/feast_spark/client.py
  python/feast_spark/job_service.py
  python/feast_spark/pyspark/abc.py
  python/feast_spark/pyspark/launcher.py
  python/feast_spark/pyspark/launchers/aws/emr.py
  python/feast_spark/pyspark/launchers/aws/emr_utils.py
  python/feast_spark/pyspark/launchers/gcloud/dataproc.py
  python/feast_spark/pyspark/launchers/k8s/k8s.py
  python/feast_spark/pyspark/launchers/k8s/k8s_utils.py
  python/feast_spark/pyspark/launchers/standalone/local.py
  tests/e2e/test_online_features.py
Labels: kind/housekeeping, lgtm, release-note, size/L

#25 Add tests for master branch
  .prow.yaml
Labels: kind/housekeeping, release-note-none

#24 Add Helm chart publishing for Feast Spark
  .github/workflows/release.yml
  infra/scripts/push-helm-charts.sh
  infra/scripts/sync-helm-charts.sh
  infra/scripts/validate-helm-chart-docker-image.sh
  infra/scripts/validate-helm-chart-versions.sh
Labels: kind/housekeeping, release-note-none, size/L

#32 Allow only project filter when listing ft
  python/feast_spark/pyspark/launchers/k8s/k8s.py
  python/feast_spark/pyspark/launchers/k8s/k8s_utils.py
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#29 Configurable retry for failed jobs (JobService Control Loop)
  .github/workflows/pr.yml
  Makefile
  infra/scripts/k8s-common-functions.sh
  pom.xml
  python/feast_spark/cli.py
  python/feast_spark/client.py
  python/feast_spark/constants.py
  python/feast_spark/job_service.py
  python/feast_spark/pyspark/launcher.py
  python/tests/test_streaming_job_scheduling.py
  spark/ingestion/pom.xml
Labels: approved, kind/feature, lgtm, release-note, size/XL
