Repository feast-dev/feast-spark, pull requests merged in 2021-03, with the labels that each got.

#35 Fix GH Actions PR Workflow Support for PRs from External Contributors
  .github/workflows/pr.yml
  .github/workflows/pr_secrets.yml
Labels: kind/bug, release-note-none, size/M

#44 Better cleanup for cached rdds in Streaming Ingestion
  pom.xml
  spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisSinkRelation.scala
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/XS

#43 Implicit type conversion for entity and feature table source
  python/feast_spark/pyspark/historical_feature_retrieval_job.py
  python/tests/data/bookings.csv
  python/tests/data/column_mapping_test_entity.csv
  python/tests/data/column_mapping_test_feature.csv
  python/tests/data/customer_driver_pairs.csv
  python/tests/data/customers.csv
  python/tests/data/single_customer.csv
  python/tests/data/transactions.csv
  python/tests/test_historical_feature_retrieval.py
Labels: approved, kind/feature, lgtm, release-note, size/XL

#45 Make field mapping for batch source consistent with streaming source
  python/feast_spark/pyspark/historical_feature_retrieval_job.py
  python/tests/test_historical_feature_retrieval.py
Labels: approved, lgtm, needs-kind, release-note, size/S

#47 Add documentation building for readthedocs.org
  .readthedocs.yml
  Makefile
  python/docs/Makefile
  python/docs/source/conf.py
  python/docs/source/feast_spark.api.rst
  python/docs/source/feast_spark.contrib.rst
  python/docs/source/feast_spark.contrib.validation.rst
  python/docs/source/feast_spark.pyspark.launchers.aws.rst
  python/docs/source/feast_spark.pyspark.launchers.gcloud.rst
  python/docs/source/feast_spark.pyspark.launchers.k8s.rst
  python/docs/source/feast_spark.pyspark.launchers.rst
  python/docs/source/feast_spark.pyspark.launchers.standalone.rst
  python/docs/source/feast_spark.pyspark.rst
  python/docs/source/feast_spark.rst
  python/docs/source/feast_spark.third_party.grpc.health.rst
  python/docs/source/feast_spark.third_party.grpc.health.v1.rst
  python/docs/source/feast_spark.third_party.grpc.rst
  python/docs/source/feast_spark.third_party.rst
  python/docs/source/index.rst
  python/docs/source/modules.rst
  python/feast_spark/client.py
  python/setup.py
Labels: approved, needs-kind, release-note-none, size/XL

#49 Fix setup.py dependencies
  Makefile
  infra/docker/jobservice/Dockerfile
  python/setup.py
Labels: approved, kind/housekeeping, release-note-none, size/XS

#28 Cleanup Scala code
  spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/BatchPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala
  spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/metrics/IngestionPipelineMetrics.scala
  spark/ingestion/src/main/scala/feast/ingestion/sources/bq/BigQueryReader.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisSinkRelation.scala
  spark/ingestion/src/main/scala/feast/ingestion/utils/TypeConversion.scala
  spark/ingestion/src/main/scala/org/apache/spark/api/python/DynamicPythonFunction.scala
Labels: approved, do-not-merge/release-note-label-needed, kind/housekeeping, lgtm, ok-to-test, size/L

#46 Bigtable as alternative Online Storage
  infra/scripts/test-end-to-end-gcp.sh
  pom.xml
  python/feast_spark/constants.py
  python/feast_spark/pyspark/abc.py
  python/feast_spark/pyspark/launcher.py
  python/feast_spark/pyspark/launchers/k8s/k8s.py
  spark/ingestion/pom.xml
  spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/BatchPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala
  spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/bigtable/BigTableSinkRelation.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/bigtable/DefaultSource.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/bigtable/SparkBigtableConfig.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/bigtable/serialization/AvroSerializer.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/bigtable/serialization/Serializer.scala
  spark/ingestion/src/test/scala/feast/ingestion/BatchPipelineIT.scala
  spark/ingestion/src/test/scala/feast/ingestion/BigTableIngestionSpec.scala
  spark/ingestion/src/test/scala/feast/ingestion/StreamingPipelineIT.scala
  spark/ingestion/src/test/scala/feast/ingestion/helpers/DataHelper.scala
Labels: approved, kind/feature, ok-to-test, release-note, size/XL
