Repository feast-dev/feast-spark, pull requests merged in 2021-09, with the labels that each got.

#96 Remove spark bigquery package download at run time
  python/feast_spark/pyspark/launchers/k8s/k8s.py
  python/feast_spark/pyspark/launchers/k8s/k8s_utils.py
Labels: release-note-none, size/S, kind/bug, approved

#97 Fix setup requirement
  python/setup.py
Labels: do-not-merge/release-note-label-needed, needs-kind, size/XS, approved

#98 Enable sql expression evaluation in fieldMapping for historical retrieval
  python/feast_spark/pyspark/historical_feature_retrieval_job.py
  python/tests/test_historical_feature_retrieval.py
Labels: release-note-none, size/S, kind/housekeeping, approved
