Repository feast-dev/feast-spark, pull requests merged in 2021-06, with the labels that each got.

#74 Log spark retrieval error message
  infra/docker/spark/Dockerfile
  protos/feast_spark/api/JobService.proto
  python/feast_spark/job_service.py
  python/feast_spark/pyspark/abc.py
  python/feast_spark/pyspark/historical_feature_retrieval_job.py
  python/feast_spark/pyspark/launchers/k8s/k8s.py
  python/feast_spark/pyspark/launchers/k8s/k8s_utils.py
  python/feast_spark/remote_job.py
Labels: approved, kind/feature, lgtm, ok-to-test, release-note-none, size/M

#75 Flush Ingestion Job termination log into kubernetes compatible destination
  python/feast_spark/remote_job.py
  spark/ingestion/src/main/resources/log4j.properties
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
Labels: approved, kind/feature, release-note-none, size/M

#77 Add configuration for bigquery entity staging location
  python/feast_spark/client.py
  python/feast_spark/constants.py
Labels: approved, lgtm, needs-kind, release-note, size/M

#78 Extra configuration for bigtable client
  spark/ingestion/src/main/scala/feast/ingestion/stores/bigtable/DefaultSource.scala
Labels: approved, kind/housekeeping, release-note-none, size/M
