Repository feast-dev/feast-spark, pull requests merged in 2021-07, with the labels that each got.

#79 Use entity source project dataset for bigquery view creation
  python/feast_spark/pyspark/launcher.py
Labels: approved, kind/bug, lgtm, release-note, size/M

#81 Make max inflight RPCs in bigtable client configurable through spark config
  spark/ingestion/src/main/scala/feast/ingestion/stores/bigtable/DefaultSource.scala
Labels: approved, kind/housekeeping, release-note-none, size/XS

#80 Use hash for schedule job id
  python/feast_spark/pyspark/launchers/k8s/k8s.py
  tests/e2e/test_job_scheduling.py
Labels: approved, kind/housekeeping, lgtm, release-note, size/S

#82 Use gcThresholdSec label (if present) instead of maxAge for feature TTL in storage
  python/feast_spark/pyspark/launcher.py
Labels: approved, kind/feature, release-note-none, size/S

#83 Refresh redis topology on write
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisSinkRelation.scala
Labels: approved, kind/bug, release-note, size/S

#84 Fix mypy-protobuf version requirement
  python/setup.py
Labels: kind/housekeeping, release-note-none, size/XS

#85 Fix mypy-protobuf version requirement for setup
  python/setup.py
Labels: approved, do-not-merge/release-note-label-needed, needs-kind

#86 Do not use gcThreshold for historical retrieval jobs
  python/feast_spark/pyspark/launcher.py
Labels: approved, kind/bug, release-note-none, size/S
