Repository feast-dev/feast-spark, pull requests merged in 2021-05, with the labels that each got.

#68 Update redis host for e2e tests
  infra/scripts/test-end-to-end-gcp.sh
Labels: approved, kind/housekeeping, lgtm, release-note-none, size/XS

#69 Batch Ingestion job is stuck after exception thrown
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#70 Fix SSTable name length restrictions during ingestion
  spark/ingestion/src/main/scala/feast/ingestion/stores/bigtable/BigTableSinkRelation.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/cassandra/CassandraSinkRelation.scala
  spark/ingestion/src/main/scala/feast/ingestion/utils/StringUtils.scala
Labels: approved, kind/bug, lgtm, ok-to-test, release-note-none, size/M

#71 Test long entity names in e2e tests
  tests/e2e/test_online_features.py
Labels: approved, kind/housekeeping, release-note-none, size/S

#72 Fix broken scheduled batch ingestion jobs
  python/feast_spark/pyspark/abc.py
  python/feast_spark/pyspark/launchers/k8s/k8s.py
  python/feast_spark/pyspark/launchers/k8s/k8s_utils.py
  tests/e2e/test_job_scheduling.py
Labels: approved, kind/bug, lgtm, release-note, size/M
