Repository feast-dev/feast-spark, pull requests merged in 2022-03, with the labels that each got.

#120 Add last processed event timestamp to streaming job
  spark/ingestion/pom.xml
  spark/ingestion/src/main/scala/org/apache/spark/metrics/source/StreamingMetricSource.scala
Labels: release-note-none, size/S, kind/feature, lgtm, approved, ok-to-test

#122 Update last processed event timestamp
  python/feast_spark/pyspark/launcher.py
Labels: size/XS, release-note-none, kind/bug, lgtm, approved, ok-to-test

#121 update dns cache ttl
  spark/ingestion/src/main/scala/feast/ingestion/BatchPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisSinkRelation.scala
Labels: do-not-merge/release-note-label-needed, needs-kind, size/XS, approved

#123 whitelist job request based on configuration
  python/feast_spark/job_service.py
  python/tests/test_jobservice_servicer.py
Labels: do-not-merge/release-note-label-needed, needs-kind, size/M, approved

#124 update version to 0.2.22
  infra/charts/feast-spark/Chart.yaml
  infra/charts/feast-spark/README.md
  infra/charts/feast-spark/charts/feast-jobservice/Chart.yaml
  infra/charts/feast-spark/charts/feast-jobservice/README.md
  infra/charts/feast-spark/requirements.lock
  infra/charts/feast-spark/requirements.yaml
  pom.xml
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
Labels: do-not-merge/release-note-label-needed, needs-kind, approved

#126 Update logic to triage healthy ingestion jobs
  python/feast_spark/pyspark/launcher.py
Labels: size/XS, kind/feature, lgtm, approved, ok-to-test

#125 Add Redis write properties
  spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisSinkRelation.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/SparkRedisConfig.scala
  spark/ingestion/src/test/scala/feast/ingestion/BatchPipelineIT.scala
  spark/ingestion/src/test/scala/feast/ingestion/PandasUDF.scala
  spark/ingestion/src/test/scala/feast/ingestion/StreamingPipelineIT.scala
Labels: size/M, approved

#127 add project label
  python/feast_spark/pyspark/abc.py
  python/feast_spark/pyspark/launcher.py
  python/feast_spark/pyspark/launchers/k8s/k8s.py
Labels: size/XS, approved

#128 update version to 0.2.23
  infra/charts/feast-spark/Chart.yaml
  infra/charts/feast-spark/README.md
  infra/charts/feast-spark/charts/feast-jobservice/Chart.yaml
  infra/charts/feast-spark/charts/feast-jobservice/README.md
  infra/charts/feast-spark/requirements.lock
  infra/charts/feast-spark/requirements.yaml
  pom.xml
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
Labels: approved

#129 update github action
  .github/workflows/master_only.yml
  .github/workflows/pr_full_access.yml
  .github/workflows/release.yml
Labels: size/S, approved

#130 Make job hashing order agnostic
  python/feast_spark/pyspark/abc.py
  python/requirements-ci.txt
  python/tests/test_launcher_abc.py
Labels: size/M, approved

#131 Exclude healthcheck calls from logging interceptor
  python/feast_spark/job_service.py
Labels: size/XS, approved

#132 Update version to v0.2.24
  infra/charts/feast-spark/Chart.yaml
  infra/charts/feast-spark/README.md
  infra/charts/feast-spark/charts/feast-jobservice/Chart.yaml
  infra/charts/feast-spark/charts/feast-jobservice/README.md
  infra/charts/feast-spark/requirements.lock
  infra/charts/feast-spark/requirements.yaml
  pom.xml
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
Labels: approved
