Repository feast-dev/feast-spark, pull requests merged in 2022-04, with the labels that each got.

#133 Perform data type conversion automatically
  Makefile
  spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/BatchPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/utils/TypeConversion.scala
  spark/ingestion/src/test/scala/feast/ingestion/BatchPipelineIT.scala
Labels: size/L, approved

#135 lock manager for job service
  Makefile
  python/feast_spark/constants.py
  python/feast_spark/job_service.py
  python/feast_spark/lock_manager.py
  python/tests/test_lock_manager.py
  python/tests/test_streaming_job_scheduling.py
Labels: size/L, needs-ok-to-test

#136 Update jobservice base image
  .github/workflows/pr.yml
  Makefile
  infra/docker/jobservice/Dockerfile
  infra/docker/spark/Dockerfile
  infra/docker/spark/dev.Dockerfile
  infra/scripts/test-end-to-end-sparkop.sh
  python/feast_spark/pyspark/historical_feature_retrieval_job.py
  python/requirements-ci.txt
  python/setup.py
  spark/ingestion/src/test/resources/python/setup.sh
Labels: size/S, approved

#137 Bundle python dependencies for spark images
  infra/docker/spark/Dockerfile
  infra/docker/spark/dev.Dockerfile
  tests/e2e/test_validation.py
Labels: size/S, approved

#134 Upgrade spark version
  .github/workflows/master_only.yml
  .github/workflows/pr.yml
  infra/docker/spark/Dockerfile
  infra/docker/spark/dev.Dockerfile
  infra/scripts/helm/k8s-jobservice.tpl.yaml
  infra/scripts/test-end-to-end-sparkop.sh
  pom.xml
  python/requirements-ci.txt
  python/setup.py
  python/tests/__init__.py
  spark/ingestion/pom.xml
  spark/ingestion/src/test/resources/python/setup.sh
  tests/requirements.txt
Labels: size/M, approved

#138 Make bigtable storage location consistent
  spark/ingestion/src/main/scala/feast/ingestion/stores/bigtable/BigTableSinkRelation.scala
Labels: size/XS, approved
