Repository feast-dev/feast-spark, pull requests merged in 2022-02, with the labels that each got.

#106 add support for redis auth
  .prow.yaml
  Makefile
  infra/scripts/test-end-to-end-aws.sh
  infra/scripts/test-end-to-end-azure.sh
  infra/scripts/test-end-to-end-gcp.sh
  python/feast_spark/constants.py
  python/feast_spark/pyspark/abc.py
  python/feast_spark/pyspark/launcher.py
  spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala
  spark/ingestion/src/test/scala/feast/ingestion/BatchPipelineIT.scala
Labels: needs-kind, size/L, release-note, approved

#107 Refactor Spark ingestion to use Jedis instead of Spark Redis
  spark/ingestion/pom.xml
  spark/ingestion/src/main/scala/feast/ingestion/BasePipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/BatchPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/ClusterPipelineProvider.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/HashTypePersistence.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/Persistence.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/PipelineProvider.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisEndpoint.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisSinkRelation.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/SingleNodePipelineProvider.scala
  spark/ingestion/src/test/scala/feast/ingestion/BatchPipelineIT.scala
Labels: needs-kind, release-note-none, size/L, approved

#109 Reduce redis hash map memory foot print
  .gitignore
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/HashTypePersistence.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/Persistence.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisSinkRelation.scala
  spark/ingestion/src/test/scala/feast/ingestion/BatchPipelineIT.scala
  spark/ingestion/src/test/scala/feast/ingestion/StreamingPipelineIT.scala
  spark/ingestion/src/test/scala/feast/ingestion/helpers/RedisStorageHelper.scala
Labels: needs-kind, size/L, release-note, approved

#110 add config setting for whitelisting feast job types
  python/feast_spark/constants.py
  python/feast_spark/job_service.py
  python/tests/test_jobservice_servicer.py
Labels: needs-kind, size/M, release-note, lgtm, ok-to-test

#111 update version to 0.2.18
  infra/charts/feast-spark/Chart.yaml
  infra/charts/feast-spark/README.md
  infra/charts/feast-spark/charts/feast-jobservice/Chart.yaml
  infra/charts/feast-spark/charts/feast-jobservice/README.md
  infra/charts/feast-spark/requirements.lock
  infra/charts/feast-spark/requirements.yaml
  pom.xml
  python/feast_spark/cli.py
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
Labels: do-not-merge/release-note-label-needed, needs-kind, size/S, approved

#112 detect whether cluster is available by cluster command
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisSinkRelation.scala
Labels: do-not-merge/release-note-label-needed, needs-kind, size/S, approved

#114 update version to 0.2.19
  infra/charts/feast-spark/Chart.yaml
  infra/charts/feast-spark/README.md
  infra/charts/feast-spark/charts/feast-jobservice/Chart.yaml
  infra/charts/feast-spark/charts/feast-jobservice/README.md
  infra/charts/feast-spark/requirements.lock
  infra/charts/feast-spark/requirements.yaml
  pom.xml
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
Labels: do-not-merge/release-note-label-needed, needs-kind, size/S, approved

#115 Add ingestion job health metrics retrieval
  protos/feast_spark/api/JobService.proto
  python/feast_spark/client.py
  python/feast_spark/constants.py
  python/feast_spark/job_service.py
  python/feast_spark/pyspark/launcher.py
  python/requirements-ci.txt
  python/setup.py
Labels: kind/feature, size/L, release-note, lgtm, approved, ok-to-test

#116 clean up Jedis connection after use
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/ClusterPipelineProvider.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/PipelineProvider.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisSinkRelation.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/SingleNodePipelineProvider.scala
Labels: do-not-merge/release-note-label-needed, needs-kind, size/M, approved

#117 update version to 0.2.20
  infra/charts/feast-spark/Chart.yaml
  infra/charts/feast-spark/README.md
  infra/charts/feast-spark/charts/feast-jobservice/Chart.yaml
  infra/charts/feast-spark/charts/feast-jobservice/README.md
  infra/charts/feast-spark/requirements.lock
  infra/charts/feast-spark/requirements.yaml
  pom.xml
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
Labels: do-not-merge/release-note-label-needed, needs-kind, size/S, approved

#118 update version to 0.2.21
  Makefile
  infra/charts/feast-spark/Chart.yaml
  infra/charts/feast-spark/README.md
  infra/charts/feast-spark/charts/feast-jobservice/Chart.yaml
  infra/charts/feast-spark/charts/feast-jobservice/README.md
  infra/charts/feast-spark/requirements.lock
  infra/charts/feast-spark/requirements.yaml
  infra/docker/spark/dev.Dockerfile
  pom.xml
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/ClusterPipelineProvider.scala
Labels: do-not-merge/release-note-label-needed, needs-kind, size/M, approved

#119 Convert maxage duration protobuf for health metric
  python/feast_spark/pyspark/launcher.py
Labels: size/XS, release-note-none, kind/bug, lgtm, approved
