Repository feast-dev/feast-spark, pull requests merged in 2022-06, with the labels that each got.

#150 Update feast dependency to 0.9.7
  python/requirements-ci.txt
  python/setup.py
Labels: size/S, approved

#151 Include protos in repository
  protos/feast/core/CoreService.proto
  protos/feast/core/DataFormat.proto
  protos/feast/core/DataSource.proto
  protos/feast/core/Entity.proto
  protos/feast/core/Feature.proto
  protos/feast/core/FeatureTable.proto
  protos/feast/core/JobService.proto
  protos/feast/core/Store.proto
  protos/feast/serving/ServingService.proto
  protos/feast/storage/Redis.proto
  protos/feast/third_party/grpc/health/v1/HealthService.proto
  protos/feast/types/Field.proto
  protos/feast/types/Value.proto
  python/setup.py
Labels: size/XXL, approved

#148 implement data validation scala to avoid python dependencies
  spark/ingestion/src/main/scala/feast/ingestion/BatchPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJob.scala
  spark/ingestion/src/main/scala/feast/ingestion/IngestionJobConfig.scala
  spark/ingestion/src/main/scala/feast/ingestion/StreamingPipeline.scala
  spark/ingestion/src/main/scala/feast/ingestion/validation/RowValidator.scala
  spark/ingestion/src/test/scala/feast/ingestion/RowValidatorTest.scala
Labels: size/L, ok-to-test

#152 Instantiate Jedis client lazily and only once per JVM process
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisSinkRelation.scala
Labels: size/S, approved

#154 Revert changes on pipeline connection initialization
  spark/ingestion/src/main/scala/feast/ingestion/errorhanders/RetryStrategy.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/ClusterPipelineProvider.scala
  spark/ingestion/src/main/scala/feast/ingestion/stores/redis/RedisSinkRelation.scala
  spark/ingestion/src/test/scala/feast/ingestion/errorhandlers/RetryStrategySpec.scala
Labels: size/L, approved

#155 Ignore cancelled job
  python/feast_spark/job_service.py
Labels: approved
